[package]

name = "rss"
version = "0.3.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/rust-rss"
documentation = "https://frewsxcv.github.io/rust-rss/rss/index.html"
description = "Library for serializing the RSS web content syndication format"
keywords = ["rss", "feed", "blog", "web", "news"]
exclude = ["test-data/"]


[dependencies]
RustyXML = "0.1"
