[package]

name = "atom_syndication"
version = "0.3.0"
authors = [
  "Francis Gagné <fragag1@gmail.com>",
  "Duncan <duncan@vtllf.org>",
  "Corey Farwell <coreyf@rwell.org>"
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/vtduncan/rust-atom"
documentation = "https://docs.rs/atom_syndication"
description = "Library for serializing the Atom web content syndication format"
keywords = ["rss", "atom", "feed", "blog"]


[dependencies]
RustyXML = "0.1"
